# Generated by Django 4.1.6 on 2023-03-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_usuario_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carrera',
            field=models.CharField(choices=[(1, 'Ingeniería de Software'), (2, 'Ingenieía en Sistemas Automotrices'), (3, 'Ingenieía Financiera'), (4, 'Ingenieria en Nanotecnología'), (5, 'Ingenieía en Tecnología Ambiental'), (6, 'Ingeniería en Logistica y Transporte'), (7, 'Ingenieía en Mecatronica'), (8, 'Ingenieía en Animación y Efectos Visuales'), (9, 'Ingenieía Agroindustrial'), (10, 'Ingenieía en Energía')], max_length=70),
        ),
    ]
