# Generated by Django 4.1.6 on 2023-03-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_usuario_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carrera',
            field=models.CharField(choices=[('IS', 'Ingeniería de Software'), ('ISA', 'Ingenieía en Sistemas Automotrices'), ('IF', 'Ingenieía Financiera'), ('IN', 'Ingenieria en Nanotecnología'), ('ITA', 'Ingenieía en Tecnología Ambiental'), ('ILT', 'Ingeniería en Logistica y Transporte'), ('IM', 'Ingenieía en Mecatronica'), ('IAEV', 'Ingenieía en Animación y Efectos Visuales'), ('IAI', 'Ingenieía Agroindustrial'), ('IE', 'Ingenieía en Energía')], max_length=70),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grado',
            field=models.CharField(choices=[('opcion1', '1'), ('opcion2', '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grupo',
            field=models.CharField(choices=[(1, 'A'), (2, 'B')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turno',
            field=models.CharField(choices=[('opcion1', 'Vespertino'), ('opcion2', 'Matutino')], max_length=100),
        ),
    ]
