# Generated by Django 4.1.6 on 2023-03-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_usuario_carrera_alter_usuario_grado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='grado',
            field=models.CharField(choices=[('opcion1', '1'), ('opcion2', '2'), ('opcion3', '3'), ('opcion4', '4'), ('opcion5', '5'), ('opcion6', '6'), ('opcion7', '7'), ('opcion8', '8'), ('opcion9', '9'), ('opcion10', '10')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grupo',
            field=models.CharField(choices=[('opcion1', 'A'), ('opcion2', 'B')], max_length=100),
        ),
    ]
