# Generated by Django 4.1.6 on 2023-03-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_alter_usuario_grado_alter_usuario_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carrera',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grupo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turno',
            field=models.CharField(max_length=100),
        ),
    ]
