# Generated by Django 4.1.6 on 2023-03-13 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_alter_usuario_carrera_alter_usuario_grado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='grado',
        ),
    ]
